version: "3.8"

services:
  app1:
    build:
      context: ./app1
    container_name: app1-container
    ports:
      - "8000:8000"
    command:
      - "--replace"

  app2:
    build:
      context: ./app2
    container_name: app2-container
    ports:
      - "8001:8001"
    environment:
      - APP1_URL=http://app1:8000
    depends_on:
      - app1
    command:
      - "--replace"
